### ISSUE TITLE
How do I access the request's context?

### ISSUE THREAD

**Issue by adarah** [awslabs/aws-lambda-web-adapter#102]
I'm building a Websocket API and I need to access the context to retrieve `$context.connectionId`. Where is the context placed after the event is processed by the web adapter?

**Comment by bnusunny** [comment]
At the moment, Lambda Web Adapter does not support Websocket API. To support it, we need to define custom http headers used to forward the context values. This is not decided yet. 

What lauguage are you using to developer the app? You can choose a lauguage specific framework to do this.

**Comment by adarah** [comment]
I see. I'm using nodejs but I wanted to avoid adding lambda specific libraries, which is why this project seemed very compelling to me. For now I'll just add something to handle my WebSocket needs.

**Comment by bnusunny** [comment]
@adarah Lambda Web Adapter version v0.6.0 is released today. In this version, the adapter will forward `requestContext` as a http header `x-amzn-request-context`. You should be able to access `connectionId` in the requestContext.
