### ISSUE TITLE
Question: accessing event and context

### ISSUE THREAD

**Issue by pogzyb** [awslabs/aws-lambda-web-adapter#107]
I'm using the go gin framework and wondering where the event payload from API GW is passed.
I see in some examples ([flask](https://github.com/awslabs/aws-lambda-web-adapter/blob/main/examples/flask/events/event.json)) there is an `event.json` file containing the payload, but don't see any example actually accessing that data within the request (unless I missed one). 

Is it possible to get at that data for purposes such as checking fields passed from authorizers?

Here's a simple example below that I've deployed and tried, but have only received null responses for `requestContext`:
```
func Handler(c *gin.Context) {
	requestContext, ok := c.Get("requestContext")
	if !ok {
		requestContext = "Nope"
	}
	c.JSON(200, gin.H{
		"message": fmt.Sprintf("ok? %v", requestContext),
	})
}
``` 

Thanks in advance!

**Comment by bnusunny** [comment]
Hello, thanks for raising this issue. At the moment, the adapter does not forward request context to the web server. 

Could you share your use cases besides using API GW for authorization?

**Comment by pogzyb** [comment]
Thanks for the quick response! Authorization is my primary use case. 
Are there plans to add this in the future?

**Comment by bnusunny** [comment]
We are considering this for the near term roadmap.

**Comment by ananthb** [comment]
I'd just like to chime in saying I'm also interested in this feature for the same reason mentioned by the author.

**Comment by pelkiegr** [comment]
I would also be interested in this.  Similar use case - deploying a small express application ephemeral on PR but need to access the request headers from within express for authorization / user identification.

**Comment by bnusunny** [comment]
Hi @pelkiegr, just to clarify, the adapter will forward regular http request headers to the web server. If a client sends a request with an authorization token as *Authorization* header, the adapter will forward to the web server. This already works. 

The OP is talking about `RequestContext` sent by the API Gateway to Lambda. It could contain auth data from Cognito or authorizers. This is not available today.

**Comment by ananthb** [comment]
@bnusunny or someone else here, any idea if I can add a custom header in API Gateway with some info from the request context and have that seen my web server running behind lambda web adapter? This would solve my problem without needing the entire request context right away.

I do need the full request context eventually because I'm doing mTLS with API Gateway and I'd like to read the raw client certs, but this could be a stop-gap until that is ready.

**Comment by ananthb** [comment]
Looks like this might be possible with a custom mapping template: https://aws.amazon.com/premiumsupport/knowledge-center/custom-headers-api-gateway-lambda/. Apologies if this is off topic.

**Comment by bnusunny** [comment]
This should be possible. I'm testing it today. I will update you soon.

**Comment by bnusunny** [comment]
This requires turning off lambda proxy integration and using a custom mapping template. But Lambda Web Adapter requires lambda proxy integration. It is not a simple task to write such a custom mapping template to match lambda proxy integration.

I'm getting close to a working prototype for sending the request context as a HTTP header. Probably has something for you next week. Stay tuned.

**Comment by pelkiegr** [comment]
> Hi @pelkiegr, just to clarify, the adapter will forward regular http request headers to the web server. If a client sends a request with an authorization token as _Authorization_ header, the adapter will forward it to the web server. This already works.
> 
> The OP is talking about `requestContext` sent by the API Gateway to Lambda ([rest api example](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format)). It could contain auth data from Cognito or authorizers. This is not available today.

I don't want to pollute this thread so let me know if I should create a new question issue.

Thanks - looking at the code that makes sense but do you have an example of this?  I pulled this repo and deployed the `expressjs` example to lambda with a function url (no api gateway) with the only change being:

```
app.get('/graphql', (req, res) => {
    console.log('HEADERS', req.headers, JSON.stringify(req.headers));
    console.log('COOKIES', req.cookies, JSON.stringify(req.cookies));

    res.send('Hi there!')
})
```

and when sending an authorization header and cookies, all I see logged is:
```
HEADERS: {"accept": "*/*","host":"127.0.0.1:8080"}
COOKIES: {}
```

**Comment by bnusunny** [comment]
@pelkiegr I did a quick test with a function url and it works. I changed the response to the following code. 

```
app.get('/', (req, res) => {
    res.send(req.headers)
})
```

The test function is here: https://y3n5ryodkiu7ruitbq5hevo6ti0hwena.lambda-url.us-west-2.on.aws/ 

Open this URL in browser. I can see all the headers sent by the browser.

**Comment by pelkiegr** [comment]
@bnusunny Ok, I can reproduce that.  I think I see my issue.  If I add a console.log of `req.headers` this is what I get in cloudwatch:

![image](https://user-images.githubusercontent.com/20116296/208115017-74f2e6ee-b61b-4657-8cc6-f566f7c16481.png)

it almost seems like on cold start I get `headers { accept: '*/*', host: '127.0.0.1:8080' }` first and then it works as expected?  I assume this is what was happening to me previously but my code was failing on the first.

**Comment by pelkiegr** [comment]
@bnusunny Ok, I can reproduce that.  I think I see my issue.  If I add a console.log of `req.headers` this is what I get in cloudwatch:

![image](https://user-images.githubusercontent.com/20116296/208115017-74f2e6ee-b61b-4657-8cc6-f566f7c16481.png)

it almost seems like on cold start I get `headers { accept: '*/*', host: '127.0.0.1:8080' }` first and then it works as expected?  I assume this is what was happening to me previously but my code was failing on the first.

**Comment by bnusunny** [comment]
Yeah. On cold start, the adapter will send readiness checks to the web server. By default, it send a http get request to `http://127.0.0.1:8080/`. That is what you saw in the log.

**Comment by ananthb** [comment]
@bnusunny, I'm concerned that exposing the request context in a header might make the header too long if there's a lot of data in the context.

The system manager lambda extension from AWS allows lambdas to retrieve system configuration and secrets from secrets manager through a localhost HTTP request from the app to a web server hosted by the extension itself.

Would it make sense for web adapter to host its own http server that can expose the request context and any other arbitrary data as needed?

Would this circumvemt the need for a custom template?

**Comment by bnusunny** [comment]
@ananthb The adapter is stateless, does not cache the request data. It is too complex to expose an http endpoint on the adapter. 

The request context usually not very big. Are you concerned about the size of clientCertPem?

**Comment by ananthb** [comment]
That makes sense. It will be too complicated to correlate requests to a second http server. I was thinking of the client cert but I'm going to be using ECDSA certs so should not be too bad honestly.

**Comment by bnusunny** [comment]
With the changes in PR #108, the adapter will forward `requestContext` in http header "x-amzn-request-context" to the web app. In web app, you need to read the value of this http header and deserialize it into JSON object. 

I will cut a new release next week with this change.
