### ISSUE TITLE
How to use sam local ?

### ISSUE THREAD

**Issue by sebsto** [awslabs/aws-lambda-web-adapter#125]
I am trying to test the container generated by `sam build`  but it fails with the following error 

```
sam local invoke -e api.json                                      
Invoking Container created from vaporhelloworld:lambda-arm64
Building image.................
Skip pulling image and use local one: vaporhelloworld:rapid-1.70.0-arm64.

START RequestId: efe70878-8fd0-4228-93bf-6d0bdc6822e7 Version: $LATEST
END RequestId: efe70878-8fd0-4228-93bf-6d0bdc6822e7
REPORT RequestId: efe70878-8fd0-4228-93bf-6d0bdc6822e7  Init Duration: 0.15 ms  Duration: 6.65 ms       Billed Duration: 7 ms   Memory Size: 512 MB   Max Memory Used: 512 MB
{"statusCode":404,"headers":{"content-type":"text/plain; charset=utf-8","x-content-type-options":"nosniff","date":"Mon, 16 Jan 2023 20:15:16 GMT","content-length":"19"},"multiValueHeaders":{"content-type":["text/plain; charset=utf-8"],"x-content-type-options":["nosniff"],"date":["Mon, 16 Jan 2023 20:15:16 GMT"],"content-length":["19"]},"body":"404 page not found\n","isBase64Encoded":false,"cookies":[]}[ NOTICE ] Server starting on http://0.0.0.0:8080
[ WARNING ] bind(descriptor:ptr:bytes:): Address already in use (errno: 98)
```

I tried to have my web application bind on `0.0.0.0` and `127.0.0.1` and they both behaves the same (`Address already in use` error)

I have the same error when using `sam local start-api`

How can I use `saml local invoke` or `sam local start-api` with the web adapter ?

**Comment by bnusunny** [comment]
Thanks for raising this issue. I should add a note in the README about local testing. 

To use sam local, the web application can't listen on port 8080. This is because the Runtime Interface Emulator already used that port. 

You can check out the Dockerfilr in the fastapi example. It listens in port 8000.

**Comment by sebsto** [comment]
Thank you @bnusunny for the quick reply. I just tested using a different port in my web app and using the PORT environment variable.  It works now with `sam local start-api` 

I suggest to keep this issue open until the README is updated
