### ISSUE TITLE
how to get apiGwStageVariables and lambdaRuntimeContext?

### ISSUE THREAD

**Issue by kumo-rn5s** [awslabs/aws-lambda-web-adapter#135]
While I can get request context events from the `x-amzn-request-context` header, how can I get apiGateway StageVariables or lambdaRuntimeContext?

Can we get it from some headers like `x-amzn-stagevars` and `x-amzn-lambda-context` for traditional lambda context?

**Comment by bnusunny** [comment]
Yes, stage variables and Lambda context are not available in the current version (v0.6.1). 

For stage variables, we could add a http header to send it to the web app. 

For Lambda Context, part of data is available in Request Context, such as request id, identity, client context. Others can be retrieved from environment variables, such as function name, function version, log group name, and log stream names. Lambda context is actually constructed from these sources. Will these cover your requirement?

**Comment by kumo-rn5s** [comment]
Cool, that would be very helpful.
