### ISSUE TITLE
terraform example

### ISSUE THREAD

**Issue by mxfactorial** [awslabs/aws-lambda-web-adapter#138]
for [several go services](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/environment/v001/lambda-services.tf) sourcing a `go-lambda-service/v001` terraform module, the module received:
1. [provided runtime](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/go-lambda-service/v001/lambda.tf#L27)
1. [READINESS_CHECK_PATH](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/go-lambda-service/v001/lambda.tf#L34)
1. [web adapter layer](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/go-lambda-service/v001/lambda.tf#L41)
1. [lambda url](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/go-lambda-service/v001/lambda.tf#L45-L48)
1. [lambda permission](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/go-lambda-service/v001/lambda.tf#L105-L112)

then the lambda package was replaced in those services with a web server, https://github.com/systemaccounting/mxfactorial/pull/270/commits/b8b3890704ffa26a1ea14dd5a1120237c7326425

the graphql service resolving the other services was switched from invoking lambda arns to lambda urls, https://github.com/systemaccounting/mxfactorial/pull/270/commits/2bfe7aad6ebeb4f0a0c088595b51b59e14fda7ee, with requests signed on [detecting a lambda env](https://github.com/systemaccounting/mxfactorial/blob/ea4818862ba6dcb5f418c482fb04dfaadc4bbad0/services/gopkg/httpclient/client.go#L34-L45)

most services were [added to containers](https://github.com/systemaccounting/mxfactorial/tree/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/docker) after removing the lambda package dependency

integration tests on the new compose stack pass, https://github.com/systemaccounting/mxfactorial/actions/runs/3961916243/jobs/6787927713

thank you harold

**Comment by bnusunny** [comment]
This is super cool! You migrated from lambda-go-api-proxy to Lambda Web Adapter. Do you mind sharing the motivation for this change? Any benefit gained? And any improvement you want to see? 

@ sapessi

**Comment by mxfactorial** [comment]
> You migrated from lambda-go-api-proxy to Lambda Web Adapter.

graphql [remains on the aws-lambda-go-api-proxy](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/services/graphql/server.go#L28) since it was previously hacked to [start a web server](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/services/graphql/server.go#L72) when [not in lambda](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/services/graphql/server.go#L57)

but several other services on the `aws-lambda-go` package, which were not running web servers, are no longer hacked to enable local development by skipping the lambda package when an event is passed through an environment variable, example: [notifications-clear](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/services/notifications-clear/cmd/main.go#L218-L225) (temporarily broken by web adapter change, but not used)

the big change for graphql was invoking the services by function url instead of arn (http vs `aws-sdk-go` lambda invoke)—now possible as the services run [web servers](https://github.com/systemaccounting/mxfactorial/blob/develop/services/request-create/cmd/main.go#L400-L421)

removing the sdk dependencies avoids web server vs lambda code and tools such as https://github.com/localstack/localstack

> Do you mind sharing the motivation for this change?

these services are intended to support a publicly used streaming data platform—and will always be on

hosting an always on [18.00/month](https://github.com/systemaccounting/mxfactorial/issues/254#issuecomment-1369381953) demo in lambda is preferred to 250.00/month in ecs/eks

> Any benefit gained?

your work paves a smooth path from low cost, per invoke cloud hosting to high performance, always on cloud hosting

in short, youve earned your "smooth scaling" badge

and this issue is expressing gratitude for your effort

heres a terraform summary for nodejs/typescript devs to encourage adoption:
1. [nodejs18.x](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/environment/v001/rules.tf#L17) managed runtime
1. [layer](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/environment/v001/rules.tf#L21)
1. run script [handler assignment](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/environment/v001/rules.tf#L16)
1. [run script](https://github.com/systemaccounting/mxfactorial/blob/develop/services/rules/run-lambda.sh)
1. AWS_LAMBDA_EXEC_WRAPPER [variable assignment](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/environment/v001/rules.tf#L29)
1. READINESS_CHECK_PATH [variable assignment](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/environment/v001/rules.tf#L30)
1. [function url](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/environment/v001/rules.tf#L35-L38)
1. [invoke function url permission](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/infrastructure/terraform/aws/modules/environment/v001/rules.tf#L85-L96)
1. [expressjs app](https://github.com/systemaccounting/mxfactorial/blob/d1717c7a6ad1d5eb90bf9f3ffcbc60f75236a46e/services/rules/src/app.ts)
1. [request signing](https://github.com/systemaccounting/mxfactorial/blob/cd26dc4d60fbb2b67dd1cae6201e6f2f86ee5e24/test/integ.test.ts#L30-L72)

> any improvement you want to see?

none, will open a different issue 

welcome to close at your convenience

**Comment by mxfactorial** [comment]
> You migrated from lambda-go-api-proxy to Lambda Web Adapter.

done in https://github.com/systemaccounting/mxfactorial/pull/272

1. add web_adapter_layer_version [terraform variable](https://github.com/systemaccounting/mxfactorial/blob/3c65e1dd714e249073541e859555b253cd076551/infrastructure/terraform/aws/modules/environment/v001/variables.tf#L26) to enable per environment [versioning](https://github.com/systemaccounting/mxfactorial/blob/3c65e1dd714e249073541e859555b253cd076551/infrastructure/terraform/aws/environments/dev/main.tf#L51)
2. add [lambda layer](https://github.com/systemaccounting/mxfactorial/blob/3c65e1dd714e249073541e859555b253cd076551/infrastructure/terraform/aws/modules/environment/v001/graphql.tf#L35)
3. add provided [lambda runtime](https://github.com/systemaccounting/mxfactorial/blob/3c65e1dd714e249073541e859555b253cd076551/infrastructure/terraform/aws/modules/environment/v001/graphql.tf#L17) to avoid `AWS_LAMBDA_EXEC_WRAPPER` and run script handler (ok with compiled go)
4. replace `lambda-go-api-proxy` with [plain web server](https://github.com/systemaccounting/mxfactorial/blob/3c65e1dd714e249073541e859555b253cd076551/services/graphql/server.go) (temp permissive cors until origins listed)
5. access cognito claim from recently added [x-amzn-request-context header](https://github.com/systemaccounting/mxfactorial/blob/3c65e1dd714e249073541e859555b253cd076551/services/graphql/auth/auth.go#L31)
