### ISSUE TITLE
Question: Why makefile is needed on python zip samples

### ISSUE THREAD

**Issue by CGarces** [awslabs/aws-lambda-web-adapter#144]
Hi.

On samples like [fastapi-zip](https://github.com/awslabs/aws-lambda-web-adapter/tree/main/examples/fastapi-zip) or [flask-zip](https://github.com/awslabs/aws-lambda-web-adapter/tree/main/examples/flask-zip) makefile is used instead of the default sam build.

Why makefile is used exacly?

**Comment by bnusunny** [comment]
It is used to keep the binaries installed by pip. We use `uvicorn` and `gunicorn` to start up the web apps. The default SAM build removes the binaries from the build output.

**Comment by CGarces** [comment]
Thanks for the clarification.
In my case I have solved the dependency with make using 
`python -m uvicorn --port=8000 app:app`

It allow me to build on windows 10 without make.
