### ISSUE TITLE
namespace the env vars

### ISSUE THREAD

**Issue by huntharo** [awslabs/aws-lambda-web-adapter#155]
Currently the `env` vars used to control the adapter are common names that may overlap with applications.

With the exception of `PORT`, perhaps the existing names should be deprecated (but still work until 1.0) and new namespaced versions should be introduced, such as `LAMBDA_ADAPTER_ASYNC_INIT`.

I'm opening this issue because I'm about to submit a PR with `COMPRESSION` as a config env var and it seems wrong to grab that name, but I also don't want to submit a PR with the only namespaced env var.

**Comment by bnusunny** [comment]
Thanks! We are thinking about this as well. We plan to namespace the environment variables with `AWS_LWA_` and support both formats until v1.0.
