### ISSUE TITLE
Release appears to be modifying prior tag Docker image

### ISSUE THREAD

**Issue by huntharo** [awslabs/aws-lambda-web-adapter#162]
After this build ran, the 0.6.1 images were modified.  I suspect that the 0.6.2 features are now present in 0.6.1.

https://github.com/awslabs/aws-lambda-web-adapter/actions/runs/4204567868

## After the 0.6.2 release branch ran

<img width="1647" alt="image" src="https://user-images.githubusercontent.com/5617868/219697337-ab3a8202-c154-4d5f-905c-40a70734b4f0.png">

## Before the 0.6.2 release branch ran

<img width="1633" alt="image" src="https://user-images.githubusercontent.com/5617868/219697090-e5f336ce-d851-4956-a9b0-d2789e716d02.png">

**Comment by bnusunny** [comment]
I'm fixing this.

**Comment by bnusunny** [comment]
Done
