### ISSUE TITLE
Error when passing a URI with non-alphanumeric characters. 

### ISSUE THREAD

**Issue by caller79** [awslabs/aws-lambda-web-adapter#173]
Hi! 

I am using the layer version 13 from the us-east-1 region for intel platform (LambdaAdapterLayerX86),  to run a nextjs website on AWS Lambda.

It works well generally, except if the URI of any request contains characters like % or ñ, the runtime fails with an "Internal server error" 500, and the Lambda logs show something like:

`ERROR Lambda runtime invoke{requestId="***" xrayTraceId="***"}: lambda_runtime: InvalidUri(InvalidUriChar)`

This happens for URL's like `https://<my api gateway>/AWS%20Lambda` or `https://<my api gateway>/Año_1234`, but I am guessing it can happen with other characters in the path which are not alphanumeric. 

Next.js itself is not so restrictive about what comes in the URI, and I would like to receive these requests in the next.js application also so I can show proper content for some or beautiful not/found or error pages for others.  Is that possible? It seems the Uri class implementation in Rust may be behind all this.

**Comment by bnusunny** [comment]
Thank for reporting this issue. Do you see this issue with layer version 11? This might be related to a change in the latest version.

**Comment by bnusunny** [comment]
I have reproduced this issue with v0.6.2 and v0.6.1. I will look into the cause. 

For now, you can use layer version 10 or docker image v0.6.0, they are not affected by this issue.

**Comment by caller79** [comment]
Thanks, I will try version 10. Layer 11 was also having this issue, I can confirm since it is the one I was using just before trying 13.
