### ISSUE TITLE
Graceful shutdown explanation

### ISSUE THREAD

**Issue by dansimau** [awslabs/aws-lambda-web-adapter#202]
Hi there,

The README states:

> Enables graceful shutdown

I am trying to find some more information about how this works. I managed to find:

* [Example for expressjs](https://github.com/awslabs/aws-lambda-web-adapter/blob/6005cd0501b8993647ccb7352df9ad438144b64e/examples/expressjs/app/src/index.js#L5)
  * Hints that we might receive a SIGTERM
* [Lambda extensions docs talks about a shutdown phase](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html#runtimes-lifecycle-shutdown)
  * If I am understanding this correctly...
    * We receive a SIGTERM
    * Have between 1500-1700ms to shut down depending on whether we use an internal extension or not
      * 2s - 300ms = 1700ms, with no other extensions
      * 2s - 500ms = 1500ms, if Lambda has additional internal extensions
    * Receive SIGKILL after 2s if we have not exited

Could you please confirm this is correct when using Lambda Web Adapter?

(If so maybe we can update the README with some more info to explain it.)

Thanks!

**Comment by bnusunny** [comment]
Yes, Lambda Web Adapter is an external extension, so it enables graceful shutdown for Lambda functions. 

You found the correct example in this repo. I have another repo with more details: https://github.com/aws-samples/graceful-shutdown-with-aws-lambda

When Lambda service shut down the execution environment, it will send a SIGTERM to the runtime process group. So the web application process will receive a SIGTERM signal. 

The duration allowed for the whole shutdown phase is 2 seconds. But for the runtime process, the duration is shorter. 

- 300ms without internal extensions. 
- 500ms with internal extensions. 

The rest of the time is for external extensions to shut down. 

This diagram is a good overview of these steps.
![image](https://user-images.githubusercontent.com/12918/228705922-8d4fa7e4-d6d1-4678-a138-ef19ae417235.png)
