### ISSUE TITLE
MissingParentDirectory: Parent directory does not exist for file: opt/extensions/lambda-adapter

### ISSUE THREAD

**Issue by four43** [awslabs/aws-lambda-web-adapter#236]
When trying to run this code in Lambda, I receive the following error via `aws lambda get-function --function-name [my function]`

```
...
        "LastUpdateStatus": "Failed",
        "LastUpdateStatusReason": "MissingParentDirectory: Parent directory does not exist for file: opt/extensions/lambda-adapter",
        "LastUpdateStatusReasonCode": "InvalidImage",
...
```

This is super odd and I haven't seen it before. My Dockerfile is using:
```
# Enable Lambda triggered web server
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.7.0 /lambda-adapter /opt/extensions/lambda-adapter
```
The base image is a slightly modified python 3.10 debian buster image, which is pretty straight forward. I can run the built docker image and run the lambda-adapter, run my code. The lambda adapter seems to run okay, just sad about a rather large list of missing env vars I didn't provide it:
```
root@ae40522af9b0:/app# /opt/extensions/lambda-adapter 
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))', /app/src/lib.rs:242:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Missing AWS_LAMBDA_FUNCTION_VERSION env var: NotPresent', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lambda_runtime-0.8.0/src/lib.rs:70:62
```
Everything seems fine from what I can emulate locally, even with that initial panic. I was unable to expand those stack traces to anything meaningful, just some memory offsets.

What more can I provide to debug? Is this something any of you have seen before? I can try and make a minimal repro example.

Thanks!

**Comment by four43** [comment]
Ah ha! I think I figured it out. My base image was doing other lambda things and I had the `aws-lambda-rie` in there. The entrypoint and command were totally different in this built image. I'll it up to you folks who are smarter than me to figure that one out!

**Comment by bnusunny** [comment]
Glad to see you figure it out. Yes, Lambda provided base images use `lambda rie` as entrypoint. You need to override it or use other base images. I do mention about this in the README. 

```
This works with any base images except AWS managed base images. To use AWS managed base images, you need to override the ENTRYPOINT to start your web app.
```

**Comment by four43** [comment]
@bnusunny - I did override the entrypoint, just later in the Dockerfile. I'm still chasing a ghost here. Some order or something is very particular since I can get the image to build locally and push to lambda just fine, but in my CI it's being more finicky.

**Comment by bnusunny** [comment]
Do you mind sharing the Dockerfile? Or a minimal example to reproduce it?

**Comment by four43** [comment]
Absolutely! I'm going to find this smoking gun dang it!

**Comment by four43** [comment]
Alright, after messing with this today I found that the install script I was using to install NodeJS was in some way messing with something your code was using. I have no idea why. 

If this is run after COPY ./lambda-adapter, it fails. If run before, it works fine. 

https://deb.nodesource.com/setup_18.x

This is so odd and niche I don't think it's worth anyone's time to investigate but I'll leave this here in case some other poor sucker comes googling with a similar issue. Thanks for the support @bnusunny.
