### ISSUE TITLE
Lambda context

### ISSUE THREAD

**Issue by mkdynamic** [awslabs/aws-lambda-web-adapter#244]
Is it possible to access the Lambda context from the request?

Looks like the current context header is being set from the event payload vs. from the actual Lambda context: https://github.com/awslabs/aws-lambda-web-adapter/blob/main/src/lib.rs#L332
 
Specifically, I need to access the requestId from that context (i.e. this https://docs.rs/lambda_http/latest/lambda_http/struct.Context.html), since I am invoking Lambda directly (constructing an event payload that is conformant with ALB or API-GW formats) where I do not have access the the actual Lambda request ID.

Related somewhat to https://github.com/awslabs/aws-lambda-web-adapter/issues/216 since this ultimately stems from calling Lambda running the LWA that are not truly from a web request.

**Comment by bnusunny** [comment]
Yes, the request context header is not the same as Lambda context. To pass the values to the web app, we probably need to use another header like "x-amzn-lambda-context".
