### ISSUE TITLE
publish ecr image push and publish-layer-version events

### ISSUE THREAD

**Issue by mxfactorial** [awslabs/aws-lambda-web-adapter#247]
>  automatic (I wish!) upgrades of layers

https://github.com/awslabs/aws-lambda-go-api-proxy/issues/143#issuecomment-1415812927

while no one responsible for a production env would require automatic layer upgrades, notifying web adapter users of new images and layers is convenient

please add:
1. eventbridge rules:
    1. [image push](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr-eventbridge.html#ecr-eventbridge-bus)
    1. `publish-layer-version` (feature absent but can send [custom event](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-putevents.html#eb-send-events-aws-cli) from your layer workflow)
1. allow `"events:PutEvents"` to `"arn:aws:events:*"` [permission](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-bus-perms.html#eb-event-bus-example-policy-cross-account) from your account
1. minimal event consumption config to doc

then users can [enable receipt](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CloudWatchEvents-CrossAccountEventDelivery.html#ReceivingEventsFromAnotherAccount) in their accounts and trigger regression test workflows, etc

also, consider templating the solution so colleagues supporting other images and layers can easily use

**Comment by bnusunny** [comment]
Thanks for the suggetion! Using Eventbridge to catch the new image or layer events are neat. But directly sending events to anther account's default bus has an scaling issue: a single EventBus has a 2000 rules limit. 

Are you open to other types of notification? Such as subcribe to a SNS topic? SNS is the purpose built notification service, which can fan out to millions' targets. 

And of cause, SNS can trigger a Lambda function, which PutEvents to Default Event Bus in the user accounts.

**Comment by mxfactorial** [comment]
> has a scaling issue: a single EventBus can have up to 2000 rules

you can allow events from [all AWS accounts](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CloudWatchEvents-CrossAccountEventDelivery.html#SendingEventsToAnotherAccount), but wildcarded targets not supported, ok

this feature wouldnt be a nightmare to add: if account A rule target has *, look up event patterns [referencing account A](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CloudWatchEvents-CrossAccountEventDelivery.html#WritingRulesThatMatchEventsFromAnotherAccount)

> Are you open to other types of notification?

yes

> Such as subcribe to a SNS topic?

yes

**Comment by CGarces** [comment]
+1 for the SNS topic.
