### ISSUE TITLE
ConnectionRefused with version 16

### ISSUE THREAD

**Issue by jeffmercerVG** [awslabs/aws-lambda-web-adapter#250]
I have a SpringBoot app that was working with version 15 of the layer.  When I upgraded to verison 16, I started seeing a semi-sporadic ConnectionRefused error.  When I rolled it back to version 15, the errors went away.  I'm having a hard time determining which tags line up with which layer version.  Can I get a mapping of layer version to git tag?  I would like to look at the diff between the two versions to see what changed.  Here is the semi-redacted error message:

`ERROR Lambda runtime invoke{requestId="xxxxxxxxxxxxxxx" xrayTraceId="Root=xxxxxxxxxxxxxxxxx"}: lambda_runtime: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))`

**Comment by bnusunny** [comment]
Layer 16 is v0.7.0, and layer 15 is v0.6.4. 

What is the SpringBoot's keep alive timeout?

**Comment by jeffmercerVG** [comment]
I don't have anything specified for keepalive, but upon further research, it looks like I was wrong about the layer versions.  It was an upgrade from 10->16, not 15->16.  This is a much bigger change.  I'm going to try to identify the exact layer version that potentially caused the impact.

**Comment by jeffmercerVG** [comment]
As my team investigated this more, we came to the conclusion that the sporadic nature of the issue made it seem like the upgrade was at fault.  It turns out it wasn't the upgrade.  We are still trying to figure it out, but I'm going to close out this issue since it seems like it was a false alarm.  Sorry about the worry.
