### ISSUE TITLE
Add support for changing the minimum healthy status code

### ISSUE THREAD

**Issue by jeffmercerVG** [awslabs/aws-lambda-web-adapter#251]
I have a use case where I am running Envoy and OPA in front of a SpringBoot app with the Lambda Web Adapter.  While OPA is starting up, Envoy will return a 4xx error code.  The Lambda Web Adapter sees the 4xx as less than 500 and thinks the app has successfully started up.  I would like an option to change the definition of unhealthy in the LWA
Note: I have a PR incoming for this.

**Comment by bnusunny** [comment]
Thanks for this contribution. This is indeed necessary.
