### ISSUE TITLE
Optional start

### ISSUE THREAD

**Issue by lijok** [awslabs/aws-lambda-web-adapter#262]
I'm trying to package both https://github.com/aws/aws-lambda-python-runtime-interface-client and this extension into a base Docker image so our service developers need to publish a single image containing their webserver and SQS/SNS/etc handler code.
The problem ofcourse is that if we're running in SQS handler mode, this extension will start up anyway and run into various error states.
I've tried to add a simple bash script that conditionally invokes this extension (which is placed outside /opt/extensions), but apparently Lambda considers an extension `exit 0` to be a crash.

Feel free to say no, but would it make sense to have a flag for this extension which when set, would cause this extension to do nothing?
Any other ideas are greatly appreciated

**Comment by bnusunny** [comment]
This is an interesting use case. Lambda service will automatically start any executables unders "/opt/extensions" directory. 

In your bash script, you need to implement two API calls for extension API: `register` and `next`. Details are in [lambda developer guide](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html). You can use `curl` to send those requests.

**Comment by lijok** [comment]
[Issue 216](https://github.com/awslabs/aws-lambda-web-adapter/issues/216) would actually remove the need for this for us
