### ISSUE TITLE
AWS_LWA_READINESS_CHECK_PORT not being picked up correctly

### ISSUE THREAD

**Issue by sidekick-eimantas** [awslabs/aws-lambda-web-adapter#263]
Minor issue - according to the docs, AWS_LWA_READINESS_CHECK_PORT defaults to whatever the value of AWS_LWA_PORT is. However, in testing I see a behaviour where if I don't set AWS_LWA_READINESS_CHECK_PORT to 8000 explicitly, the Lambda wont function, leading me to think, resolution of the AWS_LWA_READINESS_CHECK_PORT env var might be incorrect, or the docs could be worded better.

This times out:
<img width="1354" alt="image" src="https://github.com/awslabs/aws-lambda-web-adapter/assets/111279287/8ed4315c-dc70-42c5-a1d1-9168473e5fb5">

This does not:
<img width="1346" alt="image" src="https://github.com/awslabs/aws-lambda-web-adapter/assets/111279287/28ab799e-e210-4c83-8ca4-7d5da3677fbf">

**Comment by bnusunny** [comment]
Oh, the code is in main branch, but not yet released. We'll cut a minor release soon.

**Comment by bnusunny** [comment]
We are working on a few updates to the deployment pipeline. Once that is done, we will publish the new release.

**Comment by bnusunny** [comment]
v0.7.1 is released.
