### ISSUE TITLE
Base64 encoding incorrectly applied to application/jwk-set+json

### ISSUE THREAD

**Issue by jeremyhewett** [awslabs/aws-lambda-web-adapter#265]
It seems the adapter treats a response with Content-Type header `application/jwk-set+json` as binary and base64 encodes it. The response should actually be plain JSON.

Specific scenario: I'm deploying an application based on [node-oidc-provider](https://github.com/panva/node-oidc-provider), and the `/jwks` endpoint returns a base64 encoded string instead of plain JSON. The Content-Type header set by node-oidc-provider is `application/jwk-set+json` which is not configurable (and is apparently the correct value for this response). When I do change it to `application/json` (with a hack), then I get the correct response in plain JSON.

**Comment by bnusunny** [comment]
Which version of the adapter did you see this problem? The adapter relies on lambda-http crate from AWS Lambda Rust Runtime to processing the response. lambda-http crates does treat "+json" suffix as text. [Here](https://github.com/awslabs/aws-lambda-rust-runtime/blob/393d6447bea0502e1f939d197f4facc228e6e007/lambda-http/src/response.rs#L36C70-L36C70) is the link to the code. 

And as related note, lambda-http crate won't be able to cover all text based contexn-types. In v0.8.0, lambda-http treats the following content-types as text. 

Prefixes:

- "text"
- "application/json"
- "application/javascript"
- "application/xml"
- "application/yaml"

Suffixes:

-  "+xml"
-  "+yaml"
-  "+json"

For other content-types, lambda-http will treat them as binary data and base64 encode it. And if you use API Gateway REST API to trigger the Lambda function, you need to configure binaryMediaTypes to handle the binary response. Details are in API Gateway Developer guide [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html).

**Comment by mluksch** [comment]
Same here with graphql-yoga + nextjs. With "Content-Type"-Response Header: "application/graphql-response+json; charset=utf-8". Is the charset a problem here maybe?

**Comment by bnusunny** [comment]
Oh, the charset part causes the issue. This code [here](https://github.com/awslabs/aws-lambda-rust-runtime/blob/393d6447bea0502e1f939d197f4facc228e6e007/lambda-http/src/response.rs#L278) assumes Content-Type ends with the media type, which is not true. 

I will fix this issue in Rust Runtime first.

**Comment by mluksch** [comment]
Awesome. Thank you :)
