### ISSUE TITLE
InvokeMode: RESPONSE_STREAM, Python Lambda

### ISSUE THREAD

**Issue by KentonParton** [awslabs/aws-lambda-web-adapter#268]
Some great work was done to add `InvokeMode: RESPONSE_STREAM` to the `aws-lambda-web-adapter` and there are a number of Node examples floating around online showing how to use it but none for Python.

When using the `aws-lambda-web-adapter`, is `InvokeMode: RESPONSE_STREAM` supported for Python and would anyone be willing to share their `handler` implementation.

Thanks!

Related:
https://github.com/awslabs/aws-lambda-web-adapter/pull/204
https://github.com/awslabs/aws-lambda-web-adapter/issues/203

**Comment by bnusunny** [comment]
HI Kenton, Lambda Web Adapter does support web applications on Python Runtime as well, including response streaming. 

We have an example showing FastAPI response streaming [here](https://github.com/awslabs/aws-lambda-web-adapter/tree/main/examples/fastapi-response-streaming). Check it out and feel free to ask questions.

**Comment by KentonParton** [comment]
Hey @bnusunny thanks so much for linking me to the example! I just realised that aws-lambda-web-adapter is catered towards web runtimes instead of the native lambda runtimes to support frameworks like FastAPI, NextJS etc.

A couple questions:
1. If my objective is to add response steaming to an existing native Python runtime, should I be using aws-lambda-web-adapter? If no, is there a more optimal/lightweight solution for Python like there is for Node as outlined in [this blog post?](https://aws.amazon.com/blogs/compute/introducing-aws-lambda-response-streaming/). If I should be using aws-lambda-web-adapter see point 2.
2. I see that the example uses Uvicorn/FastAPI. How would you recommend leveraging response steaming with minimal dependencies and baring in mind that I am coming from the native Python runtime?

Thanks for your help.

**Comment by bnusunny** [comment]
Here are the answers: 

1. No. The current versions of managed Python Runtime do not support response streaming. 
2. Lambda Web Adapter works with Web Apps/Http APIs. Any Python API framework will do. FastAPI and Flask are the most popular choices. You could run them without Uvicorn or Gunicorn.

**Comment by KentonParton** [comment]
Thanks @bnusunny. Re "You could run them without Uvicorn or Gunicorn", are you referring to using the managed runtimes outlined [here](https://github.com/awslabs/aws-lambda-web-adapter#lambda-functions-packaged-as-zip-package-for-aws-managed-runtimes)

**Comment by bnusunny** [comment]
Yes, Lambda Web Adapter can be used with Python Runtime to enable response streaming with Function URLs. 

At the monent, Lambda response streaming only works with Lambda Function URLs and direct SDK integration via [InvokeWithResponseStream](https://docs.aws.amazon.com/lambda/latest/dg/API_InvokeWithResponseStream.html). API Gateway and ALB do not support response streaming yet.
