### ISSUE TITLE
Node 18 runtime support

### ISSUE THREAD

**Issue by amoore108** [awslabs/aws-lambda-web-adapter#274]
Hello 👋 

We are looking to update our Lambda functions to Node 18.x. We are making use of the aws-lambda-web-adapter, but notice that the supported runtime tops out at Node 16.x.

Are there plans to update this to Node 18.x?

<img width="810" alt="Screenshot 2023-08-22 at 10 17 16" src="https://github.com/awslabs/aws-lambda-web-adapter/assets/11633031/bf85fdcf-245e-473b-9fbc-4f6c40fd8533">

**Comment by bnusunny** [comment]
Hi Aaron, Lambda Web Adapter already supports Node 18.x. The adapter is a static compiled rust binary. It works on any Amazon Linux 2 based runtimes. 

We forgot to update the "compatible runtimes" property on the Layer. Actually we could just remove it. It won't effect the usage of the layer.

**Comment by amoore108** [comment]
Ah amazing, that makes sense. Thanks for clarifying!
