### ISSUE TITLE
Deploy as layer to regions in GovCloud partition: `us-gov-east-1` and `us-gov-west-1`

### ISSUE THREAD

**Issue by krrg** [awslabs/aws-lambda-web-adapter#277]
Currently the aws-lambda-web-adapter seems to be available in all major regions and partitions with the exception of AWS GovCloud (US). 

Would it be possible to publish the layer to the us-gov-east-1 and us-gov-west-1 regions as well?

**Comment by bnusunny** [comment]
Hi Ken, 

Thanks for sharing the interest on using Lambda Web Adapter in GovCloud. We do not have plans to support GovCloud in the near term.

However, if you could package your functions as container iamges, you could pull Lambda Web Adapter from ECR Public repo, and add it to your image. Another way is to download the layer contents from commercial regions and create your own layers in GovCloud.

**Comment by krrg** [comment]
Thanks for the response; I chose to simply download the layer from commercial and reupload it to a layer in GovCloud for right now, and that seems to be working. There will be some additional maintenance from AWS GovCloud customers to keep those two layers in sync, so it would be nice to see this as an eventual improvement, especially since the other partitions are supported.

**Comment by bnusunny** [comment]
I will pass the request to the team. In the meantime, you can watch issue #247 . It should be easy to automate syncing the layers from Commercial to GovCloud.

I will close this issue for now.
