### ISSUE TITLE
InvokeMode: RESPONSE_STREAM, Python Lambda Container

### ISSUE THREAD

**Issue by bgonzalezfractal** [awslabs/aws-lambda-web-adapter#278]
I've been trying to deploy an API build with FastAPI and using aws-lambda-web-adaptar to stream results. The API works fine locally and streams well, but when I deploy using container images it does not stream back, but waits for the request to be finished.

I've follow:
- https://github.com/awslabs/aws-lambda-web-adapter/issues/268
- https://aws.amazon.com/blogs/compute/using-response-streaming-with-aws-lambda-web-adapter-to-optimize-performance/
- https://github.com/awslabs/aws-lambda-web-adapter/tree/main/examples/fastapi-response-streaming

The example is quite simple with SAM, we need it to be a container image so we can handle installations of packages nicely.

I'm using Magnum to release the API

Dockerfile:
```
ARG FUNCTION_DIR="/function"

FROM python:3.9-slim-buster as build-image

#Clean up apt-get cache
RUN rm -rf /var/lib/apt/lists/*


# Include global arg in this stage of the build
ARG FUNCTION_DIR
# Create function directory
RUN mkdir -p ${FUNCTION_DIR}
RUN mkdir -p /tmp/matplot

RUN apt-get -y update
RUN apt-get install build-essential gcc -y

# Copy function folder
COPY requirements.txt ${FUNCTION_DIR}

RUN pip install -r ${FUNCTION_DIR}/requirements.txt

COPY . ${FUNCTION_DIR}

# Install the runtime interface client
RUN pip install \
  --target ${FUNCTION_DIR} \
  awslambdaric

# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}

COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.7.0 /lambda-adapter /opt/extensions/lambda-adapter
ENV PORT=8000
ENV AWS_LWA_INVOKE_MODE=response_stream
ENV AWS_LWA_READINESS_CHECK_PORT=8000

ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD [ "main_lambda2.handler" ]
```

This should handle the deploy of FastaPI in the 8000 port as well as the web adapter.

This is the endpoint in FastAPI:
```
@app.post("/stream_agent")
def stream(body: StreamRequest):
    headers = {
        "Content-Type":"application/vnd.awslambda.http-integration-response",
    }
    return StreamingResponse(send_message_agent(body.message), media_type="text/event-stream", headers=headers)
```

The Function URL actually returns a response encoded in base64, but it doest not stream it, could anyone help me here?

**Comment by bnusunny** [comment]
Thanks for raising this question. With Lambda Web Adapter, you don't need to install Lambda RIC. 

So in your Dockerfile, you need to modify the last two lines. 

```dockerfile
ENTRYPOINT [ "/usr/local/bin/python" ]
CMD [ "main_lambda2.handler" ] # change this to start your FastAPI app
```

Let me know if this works for you.

**Comment by bgonzalezfractal** [comment]
@bnusunny thanks! 

The working version has only CMD for anyone that steps upon this.
```COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.7.0 /lambda-adapter /opt/extensions/lambda-adapter
ENV PORT=8000
ENV AWS_LWA_INVOKE_MODE=response_stream
ENV AWS_LWA_READINESS_CHECK_PORT=8000

CMD ["uvicorn","main_lambda:app","--host","0.0.0.0","--port","8000"]```
