### ISSUE TITLE
404 error when loading URIs containing "[]".

### ISSUE THREAD

**Issue by 0701pino** [awslabs/aws-lambda-web-adapter#294]
I am using Next.js V13.4.
With the App Router, when using slugs, the directory name employs "[]" (e.g., [slug]).
However, when I attempt to load a page using this slug, I encounter a 404 error as follows:

Failed to load resource: the server responded with a status of 404 ()
596-1f2608a42259096f.js:1  ChunkLoadError: Loading chunk 331 failed.
(error: https://xxxxxx.amazonaws.com/_next/static/chunks/app/posts/%5Bslug%5D/page-12988c10de797864.js)

When I run the same container image locally, I can successfully load page-12988c10de797864.js. I suspect that the inclusion of URL-encoded characters in the URI might be causing the load failure.

**Comment by bnusunny** [comment]
Let me take a look.

**Comment by bnusunny** [comment]
I create a demo app with Next.js v13.5.4, and created a dynamic route following [this example](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#example), and it works. 

You can try it here.

https://b0zul34ukk.execute-api.us-west-2.amazonaws.com/blog/a
https://b0zul34ukk.execute-api.us-west-2.amazonaws.com/blog/b
https://b0zul34ukk.execute-api.us-west-2.amazonaws.com/blog/c

For dynamic routes, the url does not include "[ ]", as you can see from this example. 

Please let me know if this helps you. If you still have questions, could you please provide a simple repo which can reproduce your issue?

**Comment by 0701pino** [comment]
Thank you for the verification.

Since you mentioned that it works correctly, we have investigated under what circumstances the problem is occurring.

As a result, we found that [slug] is included in the URL when a component is called in a page that uses slug and that component is running on the client.
However, when we ran it with minimal code we were able to load the URL with [slug] in it.

We will organize and investigate the situation a bit further.

Thank you for your time.

**Comment by 0701pino** [comment]
I've tested with various versions of Next.js and found that the issue occurred up to version 13.5.3.

The problematic code from version 13.5.3 now works as expected in version 13.5.4.

It turns out the issue was not related to aws-lambda-web-adapter.

I apologize for any inconvenience caused.

Thank you.
