### ISSUE TITLE
Intermittent Segfault due to IncompleteMessage and ConnectionRefused errors

### ISSUE THREAD

**Issue by sidekick-eimantas** [awslabs/aws-lambda-web-adapter#295]
Hi

We are intermittently seeing the following errors:

> ```ERROR Lambda runtime invoke{requestId="216b4cee-c278-4024-a11c-9819cc2d0ef0" xrayTraceId="Root=1-651ee4a0-098743bf1da96ae904d4d422;Parent=31c1e21b232f3046;Sampled=0;Lineage=9f52c89d:0"}: lambda_runtime: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))```

> ```ERROR Lambda runtime invoke{requestId="5b6739af-3e46-428d-a292-cde608a9b127" xrayTraceId="Root=1-6516be75-44d0f4c771b1ae3b47d56c74;Parent=728b446c27292ae9;Sampled=0;Lineage=bb56b18c:0"}: lambda_runtime: hyper::Error(IncompleteMessage)```

We're encountering this quite rarely, and have seen one burst where 20~ requests in the span of a second all resulted in these errors.

Versions:
- LWA version: 0.7.0
- Webserver: FastAPI 0.103.2

We're running behind a Lambda Function URL. The URL is public with a Route53 DNS record with authentication disabled. We're seeing these errors specifically just on two public URLs both running the same software.

Not sure where to start troubleshooting this.

Any help would be highly appreciated. Please let me know if any additional info is required.

**Comment by bnusunny** [comment]
```
DEBUG Lambda runtime invoke{requestId=""957cd2f9-07fe-4e27-bdbc-d7ef6ae91122"" xrayTraceId=""Root=1-652547df-118a05195430e4d449c2ddd2;Parent=3c4b26d85eaf880f;Sampled=0;Lineage=bb56b18c:0""}: hyper::client::pool: reuse idle connection for (""http"", 127.0.0.1:8000)
DEBUG hyper::proto::h1::io: flushed 2711 bytes
{""log_level"": ""INFO"", ""message"": ""Received event"", ""timestamp"": ""2023-10-10 12:47:29.936786+00:00"", ""function_name"": ""__call__"", ""line_number"": 43, ""module_name"": ""_root"", ""module_path"": ""/usr/local/lib/python3.10/site-packages/event_gateway/ingest_api/routes/_root.py"", ""endpoint"": ""/rudderstack-subscriptions""}
DEBUG hyper::proto::h1::conn: parse error (connection closed before message completed) with 0 bytes
DEBUG hyper::proto::h1::dispatch: read_head error: connection closed before message completed
```

From this log, it seems FastAPI dropped the connection before sending the complete response. Did FastAPI crash?

**Comment by bnusunny** [comment]
Even for the one with 1 request processed, it actually failed. 

![image](https://github.com/awslabs/aws-lambda-web-adapter/assets/12918/2c9e9efa-6ff1-4210-a326-3cabbbe750f3)
