### ISSUE TITLE
Example `fastapi-response-streaming` with Bedrock is not working as expected

### ISSUE THREAD

**Issue by munkim** [awslabs/aws-lambda-web-adapter#299]
Hi @bnusunny, I built and deployed per instruction given in this [README](https://github.com/awslabs/aws-lambda-web-adapter/tree/main/examples/fastapi-response-streaming), but I am not able to get any answer from Bedrock. 

<img width="1728" alt="image" src="https://github.com/awslabs/aws-lambda-web-adapter/assets/17050940/f1b7c3f3-da38-4396-ad69-6c93fc2abc54">

**Comment by bnusunny** [comment]
@munkim Anthropic Claude model is not enabled by default. Please go to "Model access" menu to enable Anthropic Claude model.
