### ISSUE TITLE
How to deploy FastAPI app + LWA without SAM

### ISSUE THREAD

**Issue by munkim** [awslabs/aws-lambda-web-adapter#300]
My FastAPI application returns 142 error when using LWA. Here is what I did:

1. Added to a Dockerfile
```
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.7.1 /lambda-adapter /opt/extensions/lambda-adapter
```

2. Instead of using FastAPI handler, Dockerfile now runs a command to host a uvicorn webserver (just like a tutorial in this [tutorial](https://github.com/awslabs/aws-lambda-web-adapter/tree/main/examples/fastapi-response-streaming))
```
CMD ["python", "-m", "app_backend.main"]
```

3. Added env variables to AWS Lambda environment:  `AWS_LWA_INVOKE_MODE` (set to `RESPONSE_STREAM`) and `AWS_LWA_PORT` (set to 8080)

When I made these changes, Lambda would return 500 errors with `Error: Runtime exited with error: exit status 142 Runtime.ExitError`. Am I missing anything? 

FYI, I am using Terraform to deploy my application into a Docker container and AWS Lambda. 

![image](https://github.com/awslabs/aws-lambda-web-adapter/assets/17050940/980c3526-7fd9-4a53-be0b-94d353321f08)

**Comment by bnusunny** [comment]
@munkim You are using Lambda provided base image. You need to override the ENTRYPOINT in the Dockerfile. You can change the last line of your Dockerfile to this: 

```Dockerfile
ENTRYPOINT ["python", "-m", "app_backend.main"]
```
