### ISSUE TITLE
Example for Next Js API is missing

### ISSUE THREAD

**Issue by rahul-sharma-philips** [awslabs/aws-lambda-web-adapter#305]
An example for Next Js API is missing since the recent merge last week. Please check and revert the same. 

Readme as well are not matching.

**Comment by bnusunny** [comment]
The Next.js example was updated to Next.js v14. In Next.js v14, you can use the new App Router to build the API routes, or continue using pages router. Here is the related Next.js documentation. 

https://nextjs.org/docs/app/building-your-application/routing
