### ISSUE TITLE
CDN + API Gateway vs ALB

### ISSUE THREAD

**Issue by gsogol** [awslabs/aws-lambda-web-adapter#309]
1) How do you deploy client public frontend stuff to cloudfront? For example, using next.js. 

2) How do you choose API Gateway vs ALB? What are some questions to think through when using next.js?

thank you

**Comment by bnusunny** [comment]
Hi @gsogol, 

1. You can configure one CloudFront behavior to cache the static resources from next.js running on Lambda, with another behavior to proxy dynamic API calls. Or copy the static resources to an S3 bucket and use CloudFront to serve from it. 

2. I would recommend you to consider [Lambda Function URL](https://aws.amazon.com/blogs/aws/announcing-aws-lambda-function-urls-built-in-https-endpoints-for-single-function-microservices/) first. It provides a built-in https endpoint for your next.js app running on Lambda. It has longer timeout than 30 seconds and is completely free. It also supports response streaming, which improves TTFB and a larger payload size. It works great with next.js. Here is a [blog post](https://aws.amazon.com/blogs/compute/using-response-streaming-with-aws-lambda-web-adapter-to-optimize-performance/) with more details on response streaming.  

Harold

**Comment by gsogol** [comment]
Thanks. Regarding #2, does it support websockets? If not, what would be the next best thing?

**Comment by bnusunny** [comment]
No, Lambda function url does not support websockets. API Gateway,  AppSync and IoT Core support websockets. It requires you to change your web applications. It adds some complexity. Response streaming is much easier.

**Comment by gsogol** [comment]
We're ok with complexity on our side to enable websockets and if we continue on this path, looks like api gateway is the way to go. Having said  that, you mentioned response streaming... if we want to update another part of the page with an event that comes through, are you saying we can use response streaming instead of websockets?

**Comment by bnusunny** [comment]
If your goal is to send events to clients proactively from server side, websocket is the way to ago.

**Comment by gsogol** [comment]
Yes sir. I understand the need for painting the screen right away and hence streaming but looks like we'll do api gateway. Thank you
