### ISSUE TITLE
Issue with _X_AMZN_TRACE_ID and aws-xray-sdk in AWS Lambda

### ISSUE THREAD

**Issue by akadori** [awslabs/aws-lambda-web-adapter#312]
Thank you for creating such a wonderful library. I use it all the time.

However, there is one dissatisfaction when using this. That is, _X_AMZN_TRACE_ID is not set as an environment variable.

This is inconvenient when using aws-xray-sdk. The aws-xray-sdk determines that it is running on Lambda if the environment variable LAMBDA_TASK_ROOT exists, and goes to fetch _X_AMZN_TRACE_ID. At that time, if it cannot fetch _X_AMZN_TRACE_ID, an error occurs.

Do you have any good workarounds?

**Comment by bnusunny** [comment]
Hi @akadori, I'm glad you find this tool useful. 

No, XRay trace ID ( _X_AMZN_TRACE_ID) is not set for the web apps. The web adapter and web app are separate processes. The adapter couldn't update the web app's environment variable on each invoke. 

However, the web adapter sends the xray trace ID to the web app in a http header called `x-amzn-trace-id`. The web application has to grab its value from the http header and update environment variable. Usually you can find a middleware already exists for your web framework. For example, there is [one](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-middleware.html) for node.js. It is usually easy to write such a middle if it doesn't exit. 

Harold

**Comment by akadori** [comment]
@bnusunny 
Thank you for your response.

I understand well that it is impossible due to the process being divided. I also fully understand the workaround. I will set it up using middleware.
