### ISSUE TITLE
Streaming not working properly, only handles final message.

### ISSUE THREAD

**Issue by bgonzalezfractal** [awslabs/aws-lambda-web-adapter#314]
I'm using an async callback manager with FastAPI StreamingResponse + Uvicorn + aws lambda adapter to invoke stream instead of normal execution.

The async callback manager has a queue. I'm using OpenAI LLMs to stream the response but these are LLM agents, so they take various steps in the middle. I use the queue from the callback to stream these steps. In the localhost, the server sends every piece perfectly:
```
STREAM:
#STEP_1 (appears in 1 s)
#STEP_2 (appears 3 s later than 1)
#STEP_3 (appears 2 s later than 2)
This is a message to exemplify the final LLM response (appears 1 s later than 3)
```
Nonetheless, once I use AWS Lambda and AWS Lambda adapter, the only part that successfully streams at the right time is the final response, the steps put in the queue do not appear until the final response is ready.
```
STREAM:
#STEP_1 (appears in 7 s)
#STEP_2 (appears in 7 s)
#STEP_3 (appears in 7 s)
This is a message to exemplify the final LLM response (appears in 7 s)
```
As you can see the steps wait for the final LLM response, the LLM response is streamed properly token by token. This only happens in lambda environment.

Relevant info:
### Deploying in Dockerfile 
```
ARG FUNCTION_DIR="/function"
FROM python:3.9-slim-buster as build-image
[boilerplate]
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.7.0 /lambda-adapter /opt/extensions/lambda-adapter
ENV PORT=8000
ENV AWS_LWA_INVOKE_MODE=response_stream
ENV AWS_LWA_READINESS_CHECK_PORT=8000

#ENTRYPOINT [ "/usr/local/bin/python" ]
CMD ["gunicorn","main:app","--bind","0.0.0.0:8000","-t", "0", "-w","1","--worker-class","uvicorn.workers.UvicornH11Worker","--preload"]
```

### The streaming in FastAPI, working locally and in lambda only for llm response:
```
# Begin a task that runs in the background.
    task = asyncio.create_task(
        llm_agent.acycle({"content": message})
        )
    
    try:
        # Stream responses from AsyncCallbackManager
        async for chunk in callback_manager:
            yield f"{chunk}"
    except Exception as e_async:
        yield f"data: Error - {str(e_async)}\n\n"
    finally:
        if not task.done():
            task.cancel()
```

### Steps being put in the queue:
```
await self.async_callback_manager.queue.put('#STEP_1')
```
The streaming part from aws-lambda-adapter is not working properly. How can I approach this?

**Comment by bnusunny** [comment]
@bgonzalezfractal How did you trigger this lambda function? At the moment, only Lambda Function URLs and AWS SDK supports lambda response streaming. 

When using Lambda Function URLs, you also need to configure its invoke mode to RESPONSE_STREAM.

**Comment by bnusunny** [comment]
@bgonzalezfractal I'm closing this issue. Please reopen in case you still have this problem.
