### ISSUE TITLE
Add ENV AWS_LWA_INVOKE_MODE=response_stream in Dockerfile

### ISSUE THREAD

**Issue by thailow** [awslabs/aws-lambda-web-adapter#316]
Not sure if I oversaw sth. But isn‘t ENV AWS_LWA_INVOKE_MODE=response_stream missing in the Dockerfile of the FastAPI response streaming demo?

**Comment by bnusunny** [comment]
Hi @thailow, 

Yes, we could add that environment variable in the Dockerfile. In this example, we choose to configure it using SAM Template here. Both works. 

https://github.com/awslabs/aws-lambda-web-adapter/blob/36351ae3eaac27682d68a5cc2820cce7aa503097/examples/fastapi-response-streaming/template.yaml#L19


Harold

**Comment by thailow** [comment]
Got it, thank you for the hint!
