### ISSUE TITLE
Html Streaming for Nextjs with Api Gateway & Lambda

### ISSUE THREAD

**Issue by mluksch** [awslabs/aws-lambda-web-adapter#319]
Hello,

I want to use nextjs with aws-lambda-web-adapter and use html streaming in nextjs.

Is it possible to configure ApiGateway and Lambda with aws-lambda-web-adapter for html streaming?

Thanks

**Comment by bnusunny** [comment]
For now, API Gateway does not support lambda response streaming. Only Lambda function URLs and direct AWS SDK invokes support response streaming.

**Comment by sladg** [comment]
@mluksch you may find this useful: https://github.com/sladg/lambda-server-adapter/blob/master/examples/Next.md. In case you need caching / custom origin, you would put Cloudfront in front of Lambda ;)

**Comment by mluksch** [comment]
Thanks for your help. using a cloudfront distribution now with the function url as http origin and it works 👍 but just a minor issue that the function url is now public then. function urls can be secured with aws iam though. but cf distribution doesnt seem to work well with aws iam roles though.

**Comment by bnusunny** [comment]
Good to know it works! 

One workaround to secure the function URLs is to configure CloudFront distribution to add a secure HTTP header, and validates that header exists in your NextJs app.
