### ISSUE TITLE
allow to enable debug logging from an environment variable

### ISSUE THREAD

**Issue by tmokmss** [awslabs/aws-lambda-web-adapter#322]
It'd be great if we could enable debug logging of LWA using an environment variable such as `AWS_LWA_LOG_VERBOSITY`. 

Context: I recently investigated a possible bug of a system using LWA, and building a binary for my own and bundling it to a docker image was a bit too troublesome just to enable debug logging.

i.e. change log level here depending on an envvar.

https://github.com/awslabs/aws-lambda-web-adapter/blob/c5f55e7a02b94b6af3200754dad7c238275131bd/src/main.rs#L10-L12

p.s. the possible bug was actually not caused by LWA, but http header log in debug verbosity helped a lot to find the root cause 😄

**Comment by bnusunny** [comment]
@tmokmss this is already supported: just use `RUST_LOG` to figure the log level.

**Comment by tmokmss** [comment]
TIL about that! I confirmed `ENV RUST_LOG=debug` in Dockerfile worked, thanks. @bnusunny
