### ISSUE TITLE
Use TCP connection to check for readiness 

### ISSUE THREAD

**Issue by richarddd** [awslabs/aws-lambda-web-adapter#36]
Doing a GET request adds a lot more overhead than a simple TCP connection. If we check readiness using a TCP connection check we can save some init time. However, customers might want to provide a "readiness path" where they can lazily initialize and befit from the init boost of Lambda. My suggestion would be to default to TCP check and if `READINESS_CHECK_PATH` exists, do a GET request

```rust
match TcpStream::connect(format!("localhost:{}", port)){
            Ok(_) => break,
            Err(_) => (),
        }
```

**Comment by bnusunny** [comment]
#46 added the check for 2xx http response code to ensure the app is ready.
