### ISSUE TITLE
Error { kind: SendRequest, source: Some(hyper::Error(IncompleteMessage)) 

### ISSUE THREAD

**Issue by sebasjuancho** [awslabs/aws-lambda-web-adapter#415]
Hi, I'm facing some issues using the adapter with a Python Lambda function packaged as Docker Image using FastAPI framework. Lambda code functionality is implemented using mainly async functions and when deploying the lambda and invoking a async endpoint, the next error is shown:

`{
  "errorType": "&alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>",
  "errorMessage": "client error (SendRequest)"
}`
This does not happen for endpoints that use only sync operations. I get this response testing my lambda from AWS console using AWS_LWA_PASS_THROUGH_PATH variable for non http-triggers

And enabling RUST_LOG=debug, I just see this on logs:

`ERROR Lambda runtime invoke{requestId="52dc7925-67d8-4682-9e83-f781e93ae4da" xrayTraceId="Root=1-65fa2420-49e792476009db305da67ab2;Parent=7106713d10b989f9;Sampled=0;Lineage=19427698:0"}: lambda_runtime: Error { kind: SendRequest, source: Some(hyper::Error(IncompleteMessage)) }`

I'm running it behind a Lambda Function URL and I get the same logs using the URL. When I run this locally using `sam local start-api` it works just fine. Any idea on how to troubleshoot this correctly? Thanks in advance.

**Comment by bnusunny** [comment]
Could you share a minimum code that can reproduce this issue? And what is the trigger for the Lambda function?

**Comment by sebasjuancho** [comment]
Thanks for looking into this...I'm using [ Nemoguardrails](https://github.com/NVIDIA/NeMo-Guardrails) from a Lambda. The function is invoked using a Function URL. Here is a sample code on how it works:
```python
import json
from fastapi import FastAPI, HTTPException, Request
from nemoguardrails import RailsConfig, LLMRails

app = FastAPI()

YAML_CONFIG = """
models:
 - type: main
   engine: openai
   model: gpt-4
rails:
  input:
    flows:
      - self check input
      - allow input
prompts:
  - task: self_check_input
    content: |
      Your task is to check if the user message below complies with safety policies.

      Policy for the user messages:
      - should not contain word TEST

      User message: "{{ user_input }}"

      Question: Should the user message be blocked (Yes or No)?
      Answer:
"""
COLANG_CONTENT="""
define bot allow
  "ALLOW"

define subflow allow input
  bot allow
  stop

define bot refuse to respond
  "DENY"
"""
@app.get("/")
def get_root():
    return {"message": "FastAPI running in a Lambda function"}

@app.post("/run")
async def execute(request: Request):
    raw_body = await request.body()
    body_str = raw_body.decode('utf-8')
    payload = json.loads(body_str)
    
    config = RailsConfig.from_content(yaml_content=YAML_CONFIG,colang_content=COLANG_CONTENT)
    rails = LLMRails(config,verbose=True)
    message_content = payload["input"]
    # Generate response from guardrails service
    output = await rails.generate_async( messages=[{
        "role": "user",
        "content": message_content
    }])

    if output.get("error"):
        print(f"Error: {output.get('error')}")
        raise HTTPException(status_code=500, detail=output)

    return output
```
/run endpoint expects a simple JSON object like this:
```javascript
{"input":"Some test text"}
```
This is the Dockerfile I'm using to build the image. It is adapted from nemoguardrails docs to use AWS Lambda adapter:
```bash
FROM public.ecr.aws/docker/library/python:3.10-slim
# Copy the Lambda Adapter from the public ECR
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.8.1 /lambda-adapter /opt/extensions/lambda-adapter
# Install OS dependencies
RUN apt-get update && apt-get upgrade && apt-get install -y gcc g++ make cmake
RUN mkdir -p /myapp
COPY requirements.txt /myapp
RUN pip install --upgrade pip && pip install -r /myapp/requirements.txt --no-cache-dir --target /myapp
COPY sample.py /myapp
WORKDIR /myapp
RUN python -c "from fastembed.embedding import TextEmbedding; TextEmbedding('sentence-transformers/all-MiniLM-L6-v2');"
# Make port 8000 available to the world outside this container
ENV PORT=8000
# Start nemoguardrails service
# FastAPI
CMD exec python -m uvicorn --port=$PORT sample:app --host=0.0.0.0
```

**Comment by annStein** [comment]
Hi, I'm facing the same issue. I have a FastAPI App using the lambda adapter to trigger it via API Gateway.
My POST requests work perfectly fine. The GET route, however, throws an internal server error and the lambda logs show what @sebasjuancho mentioned:
```
ERROR Lambda runtime invoke{requestId="c39861b5-955a-447c-91e8-319222d9caad" xrayTraceId="Root=1-663756d6-69e1fdbd321ff6c230681174;Parent=09faa06e7ad0673c;Sampled=0;Lineage=5726a561:0"}: lambda_runtime: Error { kind: SendRequest, source: Some(hyper::Error(IncompleteMessage)) }
```
Did anybody find a workaround or solution for this?

**Comment by bnusunny** [comment]
`IncompleteMessage` errors usually mean your web app drops the connection. Does the app crash?

**Comment by annStein** [comment]
@bnusunny I am running the same application code on an EC2 instance (with ALB) and with the lambda adapter (with API-Gateway proxy-path). The request on the EC2 instance is successful but the one to the lambda crashes.

**Comment by bnusunny** [comment]
@annStein Lambda execution environment has a few differences with an EC2 instance, such as read-only root file system (except `/tmp`), no root permission, etc). It is better to enable debug logs and see if any error happened in your application.

**Comment by annStein** [comment]
@bnusunny I figured it out, eventually. The lambda had only 128MB RAM while the EC2 instance had 1024MB. The lambda ran into a timeout during a hash-function. This led to the fact that I couldn't see any other logs or errors. Nevertheless, thank you for looking into this!

**Comment by anentropic** [comment]
I have a similar setup (Docker, Python, Django, Gunicorn, Lambda URL)

I get this error, all the logs show is:

> 2026-01-01T04:35:11.560Z | EXTENSION Name: lambda-adapter State: Ready Events: []
> 2026-01-01T04:35:11.562Z | START RequestId: 0191826f-1838-4e00-ae37-6bf3e6dfdedf Version: $LATEST
> 2026-01-01T04:35:11.631Z | ERROR Lambda runtime invoke{requestId="0191826f-1838-4e00-ae37-6bf3e6dfdedf" xrayTraceId="Root=1-6955f97c-154ac8eb31a79bb55ed4a514;Parent=214a0d8182d2ab1d;Sampled=0;Lineage=1:f1f81005:0"}: lambda_runtime::layers::panic: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage))
> 2026-01-01T04:35:11.633Z | END RequestId: 0191826f-1838-4e00-ae37-6bf3e6dfdedf
> 

I bumped the Lambda up to 8192MB but it still occurs

it's strange that there's no errors from my app, and there doesn't seem to be any time elapsed between start of request and failure

my entrypoint script looks like:

```sh
echo "ENTRYPOINT: launching gunicorn"

exec gunicorn \
    --workers "${GUNICORN_WORKERS:-1}" \
    --threads "${GUNICORN_THREADS:-4}" \
    --worker-tmp-dir "${GUNICORN_TMP_DIR:-/tmp}" \
    --timeout "${GUNICORN_TIMEOUT:-30}" \
    --bind "0.0.0.0:${PORT:-8080}" \
    --access-logfile - \
    pgb.wsgi:application
```

I see the

> ENTRYPOINT: launching gunicorn

earlier in the logs

**Comment by bnusunny** [comment]
@anentropic sorry, I missed your comment on this closed issue. gunicorn default keepalive timeout is 2 seconds. LWA uses 4 seconds keep alive timeout. Try increase gunicorn keepalive over 4 seconds.
