### ISSUE TITLE
Any plans to publish with UTF-8 fix?

### ISSUE THREAD

**Issue by dfrankland** [awslabs/aws-lambda-web-adapter#424]
Missing UTF-8 support for URLs is a big issue for my app. Are there any plans to publish a version 0.8.2 with this fix?

PR for supporting UTF-8:
https://github.com/awslabs/aws-lambda-web-adapter/pull/390

**Comment by bnusunny** [comment]
We can publish 0.8.2 this week. 

However, that PR is for UTF-8 support in HTTP Headers. Are you having issues with UTF-8 in URLs?

**Comment by dfrankland** [comment]
I believe something is forwarding the URL in a header to my app's lambda. I'm seeing the exact same error here on request to a Next.js app with a UTF-8 character in the request URL:
https://github.com/awslabs/aws-lambda-rust-runtime/issues/786

**Comment by bnusunny** [comment]
Got it. We will publish 0.8.2 soon.

**Comment by bnusunny** [comment]
Release 0.8.2 is out. 

https://github.com/awslabs/aws-lambda-web-adapter/releases/tag/v0.8.2

**Comment by dfrankland** [comment]
I got this deployed and it totally fixed my issue 👍 Thanks for your help @bnusunny
