### ISSUE TITLE
Zip example breaks compatibility for python dependencies with layers

### ISSUE THREAD

**Issue by sansmoraxz** [awslabs/aws-lambda-web-adapter#441]
The examples for python are overwriting the environment variable for `PYTHONPATH`. The layers are stored mounted to `/opt` directory. Python dependencies from layers are mounted to `/opt/python`. This will result in code failing to import dependencies properly.

I propose updating the `run.sh` scripts to something like:

```sh
#!/bin/bash

PATH=$PATH:$LAMBDA_TASK_ROOT/bin \
    PYTHONPATH=$LAMBDA_TASK_ROOT:$PYTHONPATH:/opt/python \
    exec python -m uvicorn --port=$PORT main:app
```

Working example repo here: [sansmoraxz/fastapi-layer-zip-example-with-layers](https://github.com/sansmoraxz/fastapi-layer-zip-example-with-layers)

**Comment by bnusunny** [comment]
Thanks for reporting this issue. Would you like to push a PR?

**Comment by sansmoraxz** [comment]
Sure.
