### ISSUE TITLE
FastAPI middleware prevented from running post-request handling

### ISSUE THREAD

**Issue by KristinnVikar** [awslabs/aws-lambda-web-adapter#466]
We're running into an issue where our FastAPI lambda gets frozen before it gets to finish it's DataDog trace, since the trace is finalized after the full response has been sent to the client, which in this case is the `aws-lambda-web-adapter`.

This is causing some of our traces to report taking hours to respond to clients, which we know isn't the case. What's the recommended solution to this sort of issue? How do we make sure the FastAPI middlewares get to finish the post-request handling before the lambda invocation freezes?

**Comment by bnusunny** [comment]
One way to address this is to use an internal extension. Checkout this example [here](https://github.com/awslabs/aws-lambda-web-adapter/tree/main/examples/fastapi-background-tasks).

**Comment by KristinnVikar** [comment]
Thanks for the suggestion! 
We ended up solving it a different way by adding a middleware on the outermost layer that lets us wrap the `send` function, so that we can do our finalization code just before the end of the request is sent to the `aws-lambda-web-adapter` client.

```py
class SpanMiddleware:
    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        async def wrapped_send(message):
            if "more_body" in message and not message["more_body"]:
                scope["span"].finish()
                # Last place to run code before lambda freezes
            return await send(message)

        return await self.app(scope, receive, wrapped_send)


def span_modifier(span, scope):
    scope["span"] = span


app = SpanMiddleware(TraceMiddleware(app, span_modifier=span_modifier))
```

Where `span_modifier` is used to store the span in the request scope to use in the finalization code.
