### ISSUE TITLE
`Illegal instruction` error when running on local x86 VM.

### ISSUE THREAD

**Issue by DiscreteTom** [awslabs/aws-lambda-web-adapter#474]
Some local VM may miss some CPU instructions like AVX. Running LWA on these VMs directly or via SAM local will cause `[ERROR] (rapid) Init failed InvokeID= error=signal: illegal instruction`.

Maybe a debug build (non optimized, no extension instructions needed) should be provided for local development.

**Comment by bnusunny** [comment]
Yes, LWA x86 binary is compile with AVX2 support. Feel free to send a PR.

**Comment by bnusunny** [comment]
Closing as this is not a bug impacting customers on the Lambda service.
