### ISSUE TITLE
Extra JSON included in the streaming response when invoke by SDK

### ISSUE THREAD

**Issue by JerryWuZiJie** [awslabs/aws-lambda-web-adapter#476]
I'm using the fastapi-response-streaming example with minor modification, and I'm using flask instead of fastapi.

I enabled streaming and when sending request to the lambda function URL, the response is normal with the text streaming back.

However, when I invoke the lambda with SDK (I add a `events/` uri to handle this), an extra json will be included in the text that's streaming back, and that part seems to be the flask response metadata. For example, when I send the request with the question "x+x=1", I got the following

```
{"statusCode":400,"headers":{"server":"Werkzeug/3.0.3 Python/3.9.19","date":"Fri, 12 Jul 2024 22:47:52 GMT","content-type":"text/plain; charset=utf-8","connection":"close"},"cookies":[]}Okay, let's solve this equation:

x + x = 1

Simplifying the left-hand side:
2x = 1

Dividing both sides by 2:
x = 1/2

Therefore, the solution to the equation x + x = 1 is x = 1/2.
```

And even if the flask is responding with status code 400, the web adapter still respond with status code 200

Is this expected? Is there a way to get rid of the extra meta data in the response stream?

**Comment by bnusunny** [comment]
This is a metadata prelude to pass status code, headers and cookies for the streaming response. Lambda function URL understand it and process it before send the reponse back to client. For clients using SDK to invoke Lambda directly, the clients need to process this prelude themselves. 

I would recommand to use Function URL since it handles that and is free to use.

**Comment by JerryWuZiJie** [comment]
Thanks for the prompt reply! I'm not sure if I understand correctly, but does it mean the web adapter will wrap the entire response into the Chunked response body, and function URL can understand it and extract the metadata from the chunk and use it as the response prelude?

**Comment by bnusunny** [comment]
You got it except the last part. Function URL uses the metadata prelude to update the HTTP response status code, headers and cookies. And it only send the chunk data to the client.

**Comment by JerryWuZiJie** [comment]
Got it, thank you very much!

**Comment by ArnePannemans** [comment]
If it ever helps someone working with the SDK-based lambda streaming where the metadata prelude might be concatenated with the actual JSON content. One thing I found is that the null bytes (`\x00`) can appear in at least 3 ways:
1. Appended to the metadata prelude (but in the same JSON object)
2. In their own separate event
3. prepended to the actual payload

This is a utility function i wrote that buffers the chunks safely, removes null bytes and yields clean json objects from the stream.
```python
import json

def handle_stream(event_stream):
    decoder = json.JSONDecoder()
    buffer = ""

    for chunk in event_stream:
        if "PayloadChunk" in chunk:
            payload_bytes = chunk["PayloadChunk"]["Payload"]
            chunk_str = payload_bytes.decode("utf-8", errors="ignore").replace("\x00", "")
            buffer += chunk_str

            while True:
                buffer = buffer.lstrip()
                try:
                    parsed_obj, index = decoder.raw_decode(buffer)
                except json.JSONDecodeError:
                    break

                yield parsed_obj
                buffer = buffer[index:]

        elif "InvokeComplete" in chunk:
            break

        else:
            print("something unexpected happened")
            continue
```

And this is how to use it:

```python

try:
    response = lambda_client.invoke_with_response_stream(
        FunctionName=function_arn,
        InvocationType="RequestResponse",
        Payload=json.dumps(lambda_payload),
    )

    stream = response["EventStream"]

    for json_object in handle_stream(stream):
        print(json_object)

except Exception as e:
    print(f"Error: {e}")
```
