### ISSUE TITLE
Integration of API Gateway with FastAPI streaming server built using Lambda WebAdapter

### ISSUE THREAD

**Issue by uneetsingh** [awslabs/aws-lambda-web-adapter#490]
I have been trying to achieve streaming on Lambda created using WebAdapter. I have been able to achieve it using function url but I wish to achieve the same using API Gateway.

1. Is it possible to achieve streaming using API Gateway by creating HTTP/REST APIs with lambda as the integration target? 
2. If yes, What should be configuration for Route and REMOVE_BASE_PATH variable given that the trailing part in the GW url will be like /stage. So say I have an endpoint /api/v1/check in fastapi application housed in Lambda using webadapter, What should be the route configuration in API GW and  REMOVE_BASE_PATH in the ENV variable of Lambda. Currently for my dev stage I have set the route as /dev/{proxy+} and REMOVE_BASE_PATH = "/dev". With these configuration, I keep getting {"detail":"Not Found"} when I hit the API GW endpoint with /api/v1/check indicating that path resolution is not happening properly. Hitting ${FUNCTION_URL}/api/v1/check gives response as expected

In case the API GW using HTTP API is not possible, I am thinking to create websocket endpoints in the fastapi application and then use API GW Websocket API. 

Please suggest! Any help is deeply appreciated

**Comment by bnusunny** [comment]
API Gateway REST/HTTP API does not support response streaming. WebSocket API is a good alternative.
