### ISSUE TITLE
`aws-lambda-adapter:v.0.8.1-x86-64` doesn't return any response for Go gin framework

### ISSUE THREAD

**Issue by phat-tran-sp** [awslabs/aws-lambda-web-adapter#493]
Dockerfile: 
```Dockerfile
FROM golang:1.22-alpine as builder

WORKDIR /app

# Copy dependencies list
COPY . .

RUN apk add --update make

RUN make build
# copy artifacts to a clean image
FROM alpine:latest

COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.8.1-x86_64 /lambda-adapter /opt/extensions/lambda-adapter
COPY --from=builder /app/main /main

ENV PORT=8000 GIN_MODE=release

ENTRYPOINT [ "/main" ]
```

`./cmd/main.go`
```Go
package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()
	r.GET("/v1/certs/generate_csr", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"message": "GenerateCSR",
		})
	})
	r.Run()
}
```

Makefile:
```Makefile
clean:
	go clean

build: clean
	CC=/usr/bin/gcc GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main ./cmd/*.go
```

When I test with this event
```
{
  "body": "",
  "path": "/v1/certs/generate_csr",
  "httpMethod": "GET",
  "isBase64Encoded": false
}
```
I got this response:
![image](https://github.com/user-attachments/assets/fb5e2a92-d418-4700-9094-ed1e632f77a4)

However, when I changed to `public.ecr.aws/awsguru/aws-lambda-adapter:0.8.1-x86_64`, the response is as expected:
![image](https://github.com/user-attachments/assets/997bc939-0cba-40b5-90fb-29151aa063c8)

**Comment by bnusunny** [comment]
The test event is not in a event format sent by API Gateway, ALB or Function URL. It is treated as an non-http event by LWA. 

```json
{
  "body": "",
  "path": "/v1/certs/generate_csr",
  "httpMethod": "GET",
  "isBase64Encoded": false
}
```

**Comment by bnusunny** [comment]
@phat-tran-sp I'm closing this issue. Please feel free to reopne if you still have questions.

**Comment by phat-tran-sp** [comment]
> You need to use one of the following event template to test it.
> 
> <img alt="Screenshot 2024-08-20 at 09 39 24" width="780" src="https://private-user-images.githubusercontent.com/12918/359307410-f201ba56-1a4b-4b41-ae58-d9d84d0aeb29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzU5ODYsIm5iZiI6MTcyNTM3NTY4NiwicGF0aCI6Ii8xMjkxOC8zNTkzMDc0MTAtZjIwMWJhNTYtMWE0Yi00YjQxLWFlNTgtZDlkODRkMGFlYjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE1MDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYzRiYzk0YjYwNjAyNzYzYmE1YzlhZDYxMjg1OTEyY2FkYjI4NjJhMmJmOGVlMDJkYWQzMjBjNDBiZTU0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.koo8k5KtB-UN2DnyvJLKghfumsT4ioBKZ55NoOJSs5Y">

This is not true, I've managed to get the following request json to work for lambda adapter version `0.8.1` (up to `0.8.4`):
```json
{
  "body": "<request body>",
  "path": "/v1/certs/generate_csr",
  "httpMethod": "GET",
  "isBase64Encoded": false,
  "requestContext": {
    "httpMethod": "something"
  },
}
```
Note the extra `requestContext` field (and the subfield `httpMethod`).
I think this should be documented somewhere. And also what's the point of this when the `httpMethod` field is already declared in the root level of the request json?
