### ISSUE TITLE
Does AWS_LWA_INVOKE_MODE affect /events?

### ISSUE THREAD

**Issue by hongkongkiwi** [awslabs/aws-lambda-web-adapter#536]
I just wanted to clarify as it wasn't clear to me from the docs.

if I set AWS_LWA_INVOKE_MODE to `response_stream`, that only affects the normal http requests right?

Will it affect the /events endpoint for normal lambda events? I'm not sure if streaming makes sense for normal lambda events, only for http gateway events.

**Comment by bnusunny** [comment]
If AWS_LWA_INVOKE_MODE is set to `response_stream`, it will affect all responses. Only use it when you need response streaming. 

For non-http relates event sources, do not set it to `response_stream`, because the clients do not support it.

**Comment by hongkongkiwi** [comment]
Thanks, that's great to know. How about the readyness check? Will that be streamed to me as well if AWS_LWA_INVOKE_MODE is set to `response_stream`?

**Comment by bnusunny** [comment]
No, it won't. The responses to readiness checks are not sent to the clients.
