### ISSUE TITLE
Running other node applications and/or reverse proxying?

### ISSUE THREAD

**Issue by gkodikara** [awslabs/aws-lambda-web-adapter#57]
Hi, 

Love this adapter, have you been able to get it working with any other node library/app other than express?
I'm trying currently with directus (https://github.com/directus/directus) with external sources for db and assets but having issues with port mapping. 
I've tried various iterations using directus' docker base image and also using alpine, nginx and reverse proxying - but still have no luck. I assume this is because of the inability to communicate internally via TCP on lambda. 

Wondered if anyone had had any luck with anything similar?

Appreciate any help.

**Comment by bnusunny** [comment]
Hi Greg, 

Thanks for your interest in this tool. The adapter communicates with the web app via HTTP. Did you know which port Directus server is listening on? Directus's default port is 8055. You can specify the environment variable PORT=8055 on the lambda function. At the init phase, the adapter also sends http GET requests to the app and waits for http 2xx response. The default path is "/" for readiness checks. If Directus does not return 2xx response at "/" path, you need to find such a path and configure it via environment variable READNIESS_CHECK_PATH. 

Hope this is helpful. If you need additional support, could you please share a test container? 

Harold

**Comment by gkodikara** [comment]
Thanks for the response @bnusunny - 

`FROM directus/directus:9
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.3.3 /lambda-adapter /opt/extensions/lambda-adapter
# COPY --from=directus/directus:9 /directus /directus

ENV DB_CLIENT="mysql"
ENV DB_HOST="xxx"
ENV DB_PORT="3306"
ENV DB_DATABASE="directus"
ENV DB_USER="xxx"
ENV DB_PASSWORD="xxx"
ENV KEY="6144a906-f54b-4c74-a8f7-xxx"
ENV SECRET="Kr6x8TlAD1QLH2RcFX9hIJ-xxx"

ENV READNIESS_CHECK_PATH="/admin/login"
ENV READNIESS_CHECK_PORT=8055
ENV ASYNC_INIT="true"

EXPOSE 8055`


Here's what I have. With your Readiness check advice now. Will just try it and see.
I've tried various renditions of this using nginx and the CO
<img width="1287" alt="Screen Shot 2022-08-02 at 10 35 25 am" src="https://user-images.githubusercontent.com/735514/182267305-4b018046-c0fb-4f9d
<img width="1312" alt="Screen Shot 2022-08-02 at 10 35 57 am" src="https://user-images.githubusercontent.com/735514/182267346-c7969460-27a1-422b-acdb-38b2d095641c.png">
-b456-6d7434310ba3.png">
PY --from line you see commented out - through which I was running npx directus start and nginx (as per your example) in a run.sh file via CMD.

I'm now trying your advice and trying various versions of the above - some with asyn_init true, some with all env var's modified, or partial. The output I get is the same as attached for all though :/

This image starts directus up on load. You're right it does hit another path other than "/" -

**Comment by bnusunny** [comment]
Could you add one more environment variable? `ENV PORT=8055` This tells the adapter the web app is listening on port 8055.

**Comment by gkodikara** [comment]
Sorry should have mentioned I've tried that too but hadn't included that in the snippet above:

....
ENV PORT=8055

ENV READNIESS_CHECK_PATH="/admin/login"
ENV READNIESS_CHECK_PORT=8055
ENV ASYNC_INIT="true"

Still the same output.
Directus uses the PORT env var too could that be tripping it up? 
I will mention this flow works locally - however it often needs a refresh as directus takes a minute to start up. This is why I used your ASYNC_INIT var. 

Any other suggestions? I feel like I'm really close.

**Comment by gkodikara** [comment]
Just adding to this - this is what directus does on entry - if that makes sense - but ends up on HOST/admin/login
03:14:22 ✨ request completed GET 302 / 7ms
03:14:22 ✨ request completed GET 304 /admin 5ms
03:14:22 ✨ request completed GET 200 /admin/assets/index.917a76e9.entry.js 67ms
03:14:23 ✨ request completed GET 200 /extensions/interfaces/index.js 180ms
03:14:23 ✨ request completed GET 200 /extensions/panels/index.js 186ms
03:14:23 ✨ request completed GET 200 /extensions/displays/index.js 184ms
03:14:23 ✨ request completed GET 200 /extensions/operations/index.js 182ms
03:14:23 ✨ request completed GET 200 /extensions/layouts/index.js 187ms
03:14:23 ✨ request completed GET 200 /extensions/modules/index.js 200ms
03:14:23 ✨ request completed POST 200 /auth/refresh 177ms
03:14:23 ✨ request completed GET 304 /auth 55ms
03:14:24 ✨ request completed GET 200 /server/info?limit=-1 197ms
03:14:24 ✨ request completed GET 304 /users/me?fields[]=email&fields[]=first_name&fields[]=last_name&fields[]=last_page 93ms
03:14:28 ✨ request completed GET 200 /admin/assets/index.917a76e9.entry.js 39ms

**Comment by bnusunny** [comment]
That should work. Could you enable debug log for the Adapter by setting the environment variable `RUST_LOG=debug`?

**Comment by gkodikara** [comment]
That gives me: 

<img width="1278" alt="Screen Shot 2022-08-02 at 3 33 03 pm" src="https://user-images.githubusercontent.com/735514/182299191-c9dd2662-7955-4577-8c70-9d181567d8df.png">


Which is similar to what I got when I used reweb. Not sure where the 9001 comes from.

**Comment by bnusunny** [comment]
9001 is Lambda Runtime API's port. This is normal. 

The repeated request to http://127.0.0.1:8055/ are readiness checks. Could you go to the end of the logs? There should be some logs about `Runtime.ExitError`.

**Comment by gkodikara** [comment]
Thanks. That’s in my first screenshot - 254

**Comment by bnusunny** [comment]
Could you share your whole Dockerfile with all credentials removed?

**Comment by gkodikara** [comment]
`FROM directus/directus:9
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.3.3 /lambda-adapter /opt/extensions/lambda-adapter
# COPY --from=directus/directus:9 /directus /directus
WORKDIR "/directus"

ENV DB_CLIENT="mysql"
ENV DB_HOST="xxx-ap-southeast-2.rds.amazonaws.com"
ENV DB_PORT="3306"
ENV DB_DATABASE="directus"
ENV DB_USER="root"
ENV DB_PASSWORD="xxx"
ENV KEY="6144a906-f54b-4c74-a8f7-xxx"
ENV SECRET="Kr6x8TlAD1QLH2RcFX9hIJ-xxx"
# ENV HOST="127.0.0.1"
ENV PORT=8055

ENV READNIESS_CHECK_PATH="/admin/login"
ENV READNIESS_CHECK_PORT=8055
ENV ASYNC_INIT="true"
ENV RUST_LOG=debug

EXPOSE 8055`


This is it in it's current state. Just trying different variations of options atm

**Comment by bnusunny** [comment]
@gkodikara It looks like Directus write to extensions directory when it boots up first time. Lambda's root file system is read-only, except /tmp directory. Is there a way to pre-generate those extensions when building the docker image? 

Another workaround is to mount an EFS file system under /mnt and make symbolic links for upload and extensions folder.

**Comment by gkodikara** [comment]
This was actually the next problem I was aiming to solve - uploads and extensions. 
Uploads will be handled via S3 adapter and extensions will be COPY'd in.
Just didn't know this was why it would be crashing out.

Although there is still some fine tuning with base urls and the aforementioned uploads. It's working now. Thank you so much!

**Comment by bnusunny** [comment]
@gkodikara Welcome! Would you like to create an example for this application when it is ready?

**Comment by gkodikara** [comment]
@bnusunny yes definitely. I'm just trying to get the setup as lean as possible - Just got it saving to S3 and next going to see if I can get it running off SQLite via EFS.
Should I DM it to you or fork when ready?

**Comment by bnusunny** [comment]
Just fork and send a PR when ready. 

In addition, I would advise against putting a SQLite database on EFS. It might be okay for Dev environment, not a good idea for production environments.

**Comment by gkodikara** [comment]
Will do.

Yes definitely not for prod, just an easy one stop shop to spin up a pretty
head of the pack CMS with little overhead (thanks to your adapter).
The idea would be to work on it then migrate over to MySQL for prod or use
some form of SSR / SSG and just not have a dynamic relational layer.

But I’ll detail this when I put a PR in. Give me a couple of days.
Thanks again!
