### ISSUE TITLE
Support for `nodejs16.x` 

### ISSUE THREAD

**Issue by rohanshiva** [awslabs/aws-lambda-web-adapter#58]
When running this extension with `nodejs16.x`, getting `Error: Runtime exited with error: exit status 254 Runtime.ExitError`. But it works with `nodejs14.x`. Did anyone face this issue before? @bnusunny 

run.sh
```
#!/bin/bash

npm run start -- --port 8080
```

**Comment by bnusunny** [comment]
This error means the node.js process is terminated. Did you try the express-zip example on node16.x runtime?

**Comment by rohanshiva** [comment]
Yea I tried the express example as well with the zip option and it only works when the base lambda image is running `v16.15.0`. I noticed that sometimes the lambda function runs on `v16.16.0`, and that is when this error occurs. I am able to figure out the exact version of node because I ingested the following piece of code in run.sh
```
#!/bin/bash

node --version
npm run start
```

I also found this and ran into the same issue when using docker image on lambda with this extension and node `v16.16.0` and it seems like the culprit is node `v16.16.0`. https://repost.aws/questions/QUtlb2BYIEQjyirCUWspC-CQ/exit-254-lambda-error-with-no-extra-explanations

Not sure if there is any way to force the lambda function to use just node `v16.15.0` always.

**Comment by bnusunny** [comment]
No. Lambda service team manages the updates of the managed runtimes. If you need to use a specific version of node.js, lambda docker image is the way to go. 

I just did a few quick tests. For expressjs-zip example, I didn't run into `v16.16.0` and it worked without errors. For expressjs (docker image) example, I updated the base image to `public.ecr.aws/docker/library/node:16.16.0-slim` and it also worked with no problem. 

Could you try this base image with your function? 
`public.ecr.aws/docker/library/node:16.16.0-slim`

**Comment by rohanshiva** [comment]
I tried it with the non-slim version and it didn't work, over the last two days I didn't run into `v16.16.0` either. I wish there was a way to force/know when the lambda-managed runtime will change. Thank you so much for trying to help me resolve this issue! I will close this issue as it seems like it is not an issue with the extension.

**Comment by rohanshiva** [comment]
this is the docker file I used
```
FROM public.ecr.aws/docker/library/node:16.16.0
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.3.3 /lambda-adapter /opt/extensions/lambda-adapter
EXPOSE 8080
WORKDIR "/var/task"
ADD src/package.json /var/task/package.json
ADD src/package-lock.json /var/task/package-lock.json
RUN npm install --production
ADD src/ /var/task
CMD ["npm","run","start"]
```

**Comment by rohanshiva** [comment]
I even tried to explore the logs to see why the any `npm` command is failing by ingesting this into the `index.js` file:

```
exec("npm run start", (error, stdout, stderr) => {
    if (error) {
        console.log(`${stdout}`)
        console.log(`${stderr}`)
        console.log(`error: ${error}`);
        return;
    }
    if (stderr) {
        console.log(`stderr: ${stderr}`);
        return;
    }
    console.log(`stdout: ${stdout}`);
});
```
but all I see is this 
```
error: Error: Command failed: npm run start
```

**Comment by rohanshiva** [comment]
@bnusunny do you know how I can run this extension with the lambda-managed node base images (as in how can I override the entryfile)? I want to test it by building that Docker file locally.

**Comment by bnusunny** [comment]
Jus replace `CMD ["npm","run","start"]` with `ENTRYPOINT ["npm","run","start"]`.

**Comment by rohanshiva** [comment]
It runs `node index.js`. It doesn't matter what it runs, even `npm --version` will fail. Thank you for that

**Comment by bnusunny** [comment]
@rohanshiva I can reproduce the error with your Dockerfile. The problem seems with NPM. When I replace `CMD ["npm","run","start"]` with `CMD ["node","index.js"]`, the function works. Please try this with your function.

**Comment by rohanshiva** [comment]
Yes, I agree the problem is with NPM, but I need to use NPM for my use case which runs `next start` in the background. I used `node index .js` in this issue to so that it's simpler to understand and reproduce. I want to essentially run `next  start` through `npm run start`. Thank you for your help!

**Comment by rohanshiva** [comment]
Sure, that would be great!

**Comment by bnusunny** [comment]
Here is the [example](https://github.com/awslabs/aws-lambda-web-adapter/tree/dev/examples/nextjs).

**Comment by bnusunny** [comment]
Not at the moment. But it should be quite similar as next.js example.

**Comment by rohanshiva** [comment]
ok thanks, I don't think `nuxt` has standalone support. I could be wrong tho. Anyways, thank you so much for your help!
