### ISSUE TITLE
Why we have a "Events" config in Cloudformation yaml file? 

### ISSUE THREAD

**Issue by jinqian1998** [awslabs/aws-lambda-web-adapter#64]
I just found in all examples we use an "Events" config in CloudFormation yaml file, why we need this?
![image](https://user-images.githubusercontent.com/96728550/185872236-12cd9f7b-b42b-474d-bcea-8fa781c24b70.png)

And by the way, I checked the AWS CloudFormation document, seems there is no "Events" config option.
https://docs.aws.amazon.com/zh_cn/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html

Grateful for solve my noob issue.

**Comment by bnusunny** [comment]
@jinqian1998 This template is AWS SAM template. SAM extends CloudFormation to simplify the serverless application deployment. You can see the details here: 

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html

**Comment by jinqian1998** [comment]
Thanks for your help @bnusunny , now I understand this is a SAM template, extension of CloudFormation. 
We can close this issue now XD
