### ISSUE TITLE
Ruby Rack/Rails

### ISSUE THREAD

**Issue by metaskills** [awslabs/aws-lambda-web-adapter#67]
Hi, I maintain the Rack Lambda project. Is there an opportunity to mention how the Lamby project (https://github.com/customink/lamby) does this for Ruby and all Rack applications in Ruby like Rails, Sinatra, etc? That project is even listed as an AWS Lambda web server on Rack's page. https://github.com/rack/rack#supported-web-servers

Maybe this project can link to ours in the Acknowledgement section?

**Comment by bnusunny** [comment]
This is wonderful suggestions. I will add a section in the README for the related projects.

**Comment by metaskills** [comment]
Thanks, I added a link to this project from mine too. Cheers.
