### ISSUE TITLE
Skip readiness check?

### ISSUE THREAD

**Issue by rohanshiva** [awslabs/aws-lambda-web-adapter#82]
Is it possible to skip the readiness check?

**Comment by bnusunny** [comment]
What is your use case that has to skip the readiness check? We use the readiness check to make sure the web app is actually ready to receive requests. Otherwise, the lambda invoke will fail.

**Comment by rohanshiva** [comment]
Just wanted to check if we can ignore it, or check if a process is running on `PORT`. Which could be a better than making a request to check if web app is read.

**Comment by rohanshiva** [comment]
Yes exactly, I just want to check if the web server boots up and is listening on the PORT. If it is throwing HTTP requests, then it can fail that is fine. I am trying out this approach, but I am not sure how to build the extension to test it. Can you please let me know how I can build the extension after making modifications and test it (preferable zip)?

**Comment by rohanshiva** [comment]
@bnusunny It would be great if you can share how the zip package should look like before publishing the layer using the command : `aws lambda publish-layer-version --layer-name "lambda-adapter" --region "us-east-2" --zip-file  "fileb://extension.zip"`. 

For example, my extensions.zip has the following files
```
opt/bootstrap
opt/extensions/lambda-adapter
```

But I am having issues with this configuration.

**Comment by bnusunny** [comment]
That is the correct layout. You can use aws sam cli to build the layer. There are two SAM templates in the project root.

For example, to build and deploy x86_64 layer, use the following command. 

```shell
sam build -t template-x86_64.yaml
sam deploy --guided
```

**Comment by rohanshiva** [comment]
thank you! it works, Is there any way we can support both options by checking some flag? Here is what I did:

```rust
async fn check_web_readiness(port: u16) -> Result<i8, i8> {
    let tcp = procfs::net::tcp().unwrap();
    let tcp6 = procfs::net::tcp6().unwrap();
    for entry in tcp.into_iter().chain(tcp6) {
        // find the process (if any) that has an open FD to this entry's inode
        if entry.local_address.port() == port && entry.state == procfs::net::TcpState::Listen {
            return Ok(1)
        }
    }
    return Err(-1);
    // match reqwest::get(url).await {
    //     Ok(response) if { response.status().is_success() } => Ok(()),
    //     _ => Err(-1),
    // }
}
```

**Comment by bnusunny** [comment]
I would open an actual TCP socket to the PORT.

**Comment by rohanshiva** [comment]
Yea I agree, I think there should be a way to have both ways of checking either via making a request or via checking if a process is running on a port.
