### ISSUE TITLE
Request sent twice on cold start invocation

### ISSUE THREAD

**Issue by tmokmss** [awslabs/aws-lambda-web-adapter#95]
Hi, I see that when running an express app on Lambda with Web Adapter, a request is seemingly processed twice on a cold start.
Is it an expected behavior? 

Say I have the below express app:

```ts
const app = express();
app.get('/', async (_, res) => {
  console.log('got request');
  res.send('success');
});
```

And I see two lines of `got request` in CloudWatch logs even though I sent only one request. FYI I'm invoking Lambda via API Gateway REST API.

It is not a blocker at all but I'd like to just confirm if it is expected or not. Thanks!

**Comment by bnusunny** [comment]
That's correct. Web Adapter performs a readiness check at cold start: send http GET request to http://127.0.0.1:8080/. This makes sure the web app is up and running. You can change the readiness check path to a dedicated path by setting the environment variable READINESS_CHECK_PATH. 

If you don't want Web Adapter to send HTTP request to the web application, you can also tell the adapter to use TCP for the readiness check, by setting READINESS_CHECK_PROTOCOL=tcp. 

I would recommend to use HTTP for the readiness check. This warmup the application during the cold start and reduces invoke latency for the following invokes.

**Comment by tmokmss** [comment]
That makes sense. I'll create a dedicated endpoint for health check then. Thank you so much!
