### ISSUE TITLE
Logs are not shown

### ISSUE THREAD

**Issue by philschmid** [awslabs/aws-lambda-web-adapter#96]
Hey, 

I am using this awesome to run a `fastAPI`(Python) on Lambda, but it seems that `print` statements are not logged to cloudwatch as normally when not using the adapter. 

Is that expected?

**Comment by bnusunny** [comment]
I built a simple FastAPI app with uvicorn. The `print` contents are shown up in CloudWatch logs as expected. 

I will push the app into examples folder soon.

**Comment by philschmid** [comment]
Thank you I ll take a look. 
I use `python3 main.py` but starting the app with  `uvicorn.run()`. 

Do you know if running the app on a subprocess might have an impact? Or is everything from the stdout forwarded to cloudwatch?
